# Generated by Django 3.2.13 on 2022-05-18 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=32, null=True, verbose_name='用户名称')),
                ('upwd', models.CharField(max_length=64, null=True, verbose_name='密码')),
                ('role', models.IntegerField(choices=[(1, '学生'), (2, '老师')], verbose_name='角色')),
            ],
        ),
        migrations.CreateModel(
            name='MouldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=32, null=True)),
                ('status', models.IntegerField(choices=[(1, '通过'), (0, '待审核'), (2, '未通过')], verbose_name='状态')),
                ('createtime', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('context', models.TextField(max_length=200, verbose_name='事由')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.levelmodel', verbose_name='外键')),
            ],
        ),
    ]
