# Generated by Django 3.2.13 on 2022-05-14 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=32, verbose_name='教室名称')),
                ('script', models.CharField(max_length=64, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='EntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=32, verbose_name='学号')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('chinese', models.IntegerField(verbose_name='语文')),
                ('maths', models.IntegerField(verbose_name='数学')),
                ('english', models.IntegerField(verbose_name='英语')),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.classmodel', verbose_name='班级')),
            ],
        ),
    ]
